global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:3000']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:3001']

  - job_name: 'empleados-service'
    static_configs:
      - targets: ['empleados-service:8080']

  - job_name: 'reto6-express-service'
    static_configs:
      - targets: ['reto6-express-service:8086']

  - job_name: 'notificaciones-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notificaciones-service:8084']

  - job_name: 'perfiles-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['perfiles-service:8085']

  - job_name: 'departamentos-service'
    static_configs:
      - targets: ['departamentos-service:8081']
