sonar.projectKey=Reto6-Express-Service
sonar.projectName=Reto6 Express Service
sonar.sources=.
sonar.exclusions=node_modules/**,coverage/**,reports/**
sonar.tests=.
sonar.test.inclusions=**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
